### ISSUE TITLE
Add a section with Opal related resources

### ISSUE THREAD

**Issue by elia** [opal/opal.github.io#19]
cc @jaredcwhite @astonj

**Comment by AstonJ** [comment]
Thanks Elia.

As we were discussing at Gitter, I think a page or section listing all Opal tutorials, screencasts, blog posts etc could act as a really good resource :-)

Here's the three items I copied from the chat earlier:

- http://mike.filespanker.com/post/80464613230/opal
- http://confreaks.tv/videos/rubyconf2013-opal-a-new-hope-for-ruby-programmers
- http://funkworks.blogspot.com/search/label/opal

**Comment by jaredcwhite** [comment]
Awesome. I will add some stuff here within the next few days.

**Comment by AstonJ** [comment]
http://www.hayley365.com/2014/01/20/getting-started-with-opal-and-middleman/

**Comment by elia** [comment]
I think this is addressed by the "libraries" page (aka awesome-opal):

http://opalrb.com/libraries/
