### ISSUE TITLE
Example at "/usage" doesn't work as described

### ISSUE THREAD

**Issue by Ajedi32** [opal/opal.github.io#2]
From the text in [opalrb.org/usage](http://opalrb.org/usage/), it appears that you can get opal to compile a ruby file in `/app` simply by running a `gem install opal`, creating the following Rakefile, and running `rake build`:

``` ruby
desc "Build our app to build.js"
task :build do
  env = Opal::Environment.new
  env.append_path "app"

  File.open("build.js", "w+") do |out|
    out << env["application"].to_s
  end
end
```

I just tried this and it didn't work. I get:

```
$ rake build
rake aborted!
uninitialized constant Opal::Environment
C:/Documents and Settings/user/My Documents/Workspace/Code Sandbox/opal_test/Rakefile:5:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

So apparently there are a few steps missing in the description on that page. Could you please update it to be a bit more thorough?

**Comment by JikkuJose** [comment]
Any pointers on why this still happens?

**Comment by vais** [comment]
@davispuh @JikkuJose please see https://github.com/opal/opalrb.org/pull/17

**Comment by JikkuJose** [comment]
Thanks! I think you need to update the examples in the site.

**Comment by vais** [comment]
@JikkuJose for compiling from a rake task, you probably should not use `Opal::Server`. Here is the code that worked for me, and that I put into [this pull request](https://github.com/opal/opalrb.org/pull/17) to update the example code on the website. It uses `Opal::Builder`:
```ruby
# Rakefile
require 'opal'

desc "Build our app to build.js"
task :build do
  Opal.append_path "app"
  File.binwrite "build.js", Opal::Builder.build("application").to_s
end
```
I am by no means an expert on Opal, and I am hoping for a confirmation from the Opal core guys whether or not using `Opal::Builder` is in fact the recommended approach for this use case.

**Comment by adambeynon** [comment]
Yeap, `Opal::Builder` is the way to go now. I will merge that request in. The reason `Opal::Environment` was removed was that is was only a very simple wrapper around `Sprockets`.

**Comment by JikkuJose** [comment]
Thanks for the answers; the code seem to build, but browser console still complains of: `TypeError: Opal.modules is undefined`

Wish to clarify, can't I split the file and require the dependencies? I am getting it to compile, but the browser is giving me errors. Any pointers?

**Comment by adambeynon** [comment]
@JikkuJose Instead of loading opal from the cdn, try compiling it with your app:

```ruby
# app/application.rb
require 'opal'
require 'conway/app.rb'
```

I suspect the Opal CDN version might be out of date.

**Comment by JikkuJose** [comment]
Yup, that should be it. I got it working. But quite surprisingly:

1. `opal.min.js` didn't work (That may be because its out of date)
2. `opal.js` was created from compiling through command line.
3. Requiring opal or not didn't make any difference! Hows that? Or is it supposed to be avoided in the application file?

**Comment by adambeynon** [comment]
Looking at that repo, `opal.js` looks to be 0.7.0, so it should work fine. Simply adding it to the html file isn't enough, as that just defines all the "modules", e.g. `corelib/array` etc. You need to load them, so somewhere inside your ruby code you need to `require "opal"`, which will actually load all these core lib files.

This is a big change from 0.6, where compiled ruby was not wrapped into `Opal.modules`. This change gives us more control about loading order of files, which is critical for things like rspec and other libs to work properly.

It's good to see these problems coming up though - it gives me a better idea of what needs more documenting (and updating, in the case of the CDN).

**Comment by JikkuJose** [comment]
See,  just updated the repo, it actually worked without the require. But I have added `opal` in the html.

**Comment by vais** [comment]
@JikkuJose there are two different kinds of `require "opal"`: one in the Rakefile, another in your application file. It is not clear which one you are referring to, but both definitely make a difference: if you do not require opal in the Rakefile, nothing will work at all; if you do not require opal somewhere in your application, then opal runtime will not be included in the resulting javascript file, only the js for your application will.

For example, doing this in app/application.rb:
```ruby
# require "opal"

puts "Wow, running opal!"
```
Notice that `require "opal"` is commented out. The above produces the following small js output which is just the js of your application only:
```javascript
/* Generated by Opal 0.7.0.rc1 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts']);
  return self.$puts("Wow, running opal!")
})(Opal);
```
If you un-comment the `require "opal"` line, you will get a huge js output that includes the opal runtime in addition to your application's js.

Hope that makes sense. Happy opal hacking to you @JikkuJose :)

**Comment by JikkuJose** [comment]
Okay, cool! Now its clear! One more question: is using other Ruby gems as simple as requiring them??

**Comment by JikkuJose** [comment]
Off-topic: Will it better to compile all the required gems as separate file away from the application.

**Comment by vais** [comment]
@JikkuJose Sorry, I wish I knew the answers to these questions, but I don't yet as I'm just starting out with Opal myself :) Keep at it on Gitter!

**Comment by JikkuJose** [comment]
@vais me too :). Really wish to do all the coding in Ruby, rather that to touch JS.

**Comment by elia** [comment]
@JikkuJose if you want to have separate files in your html you have to do it manually:


To produce the single files you'd have to do something like the following:

```rb
builder = Opal::Buidler.new
builder.processed.map {|asset| [asset.filename, asset.to_s]}
```

**Comment by JikkuJose** [comment]
Oh cool, so I should be doing the following to get the assets in separate files I presume:

``` ruby
require 'opal'

desc "Compile Ruby to JS"
task :build do
  builder = Opal::Buidler.new
  builder.processed.map {|asset| [asset.filename, asset.to_s]}
  Opal.append_path "app"

  File.open("app.js", "w+") do |out|
    out << Opal::Builder.build("application").to_s
  end
end

task :default => :build
```

**Comment by JikkuJose** [comment]
I am still at loss in understanding requiring of other gems! Or is requiring `opal-browser` failing because of a problem with the gem? I am able to use `opal-jquery`.

**Comment by elia** [comment]
About multiple files it's a bit more like:

```rb
require 'opal'
require 'opal/browser'

task :build do
  Opal.append_path "app"
  
  builder = Opal::Buidler.new
  builder.build 'application'
  builder.processed.map do |asset|
    File.open("#{asset.filename}.js", "w+") do |out|
      out << asset.to_s
    end
  end
end
```

But then you'll have to find a way to require all those files into your html…

For opal-browser you just need to require `browser`, I'll add a note in the readme to clarify that.

_application.js.rb_

```rb
require 'opal'
require 'browser'
# … your code
```

**Comment by JikkuJose** [comment]
Hey! Thanks, will try that.
