### ISSUE TITLE
Getting started considered harmful

### ISSUE THREAD

**Issue by dancinglightning** [opal/opal.github.io#27]
Don't get me wrong, Opal is great. Just that guide may put more people off than get them interested.
It looks like before sprockets and even earlier days, as it talks about compiling [1,2,3] and not at all about what you can really do with opal.

As a newbie i can say what i'd expect (don't want to write it, but also not just nag)

Start with the basic choice, how to use it
- checking out -> opal server 
- medium project -> sinatra server
- rails -> rails integration
- client/server -> volt
- standalone client project including js's and go

And then explain basic steps for each. **And** links, not just links i mean.

Follow up with some roadmap through the docs, 
mention some differences ruby/opal. link to the compiler page

some basic on the choices and availability of gems (opal-browser/opal-jquery) and how to integrate those.

**Comment by vais** [comment]
:+1:

**Comment by elia** [comment]
Although it can surely be even better I think the current readme addresses most the concerns from this issue. Feedback and PRs are always appreciated.
