### ISSUE TITLE
CDN returns 404

### ISSUE THREAD

**Issue by Temikus** [opal/opal.github.io#35]
The following links 404 at the moment:

http://cdn.opalrb.com/
http://cdn.opalrb.com/opal/current/opal-parser.min.js
http://cdn.opalrb.com/opal/current/opal.min.js

**Comment by Mogztter** [comment]
I think the URL is http://cdn.opalrb.org not http://cdn.opalrb.com ?

**Comment by elia** [comment]
All the .com urls are back online, and opalrb.com is the new official URL, as a bonus they're now also available via HTTPS 🎉
