### ISSUE TITLE
https://opalrb.com/try/ uses Opal 0.11.4 ?

### ISSUE THREAD

**Issue by Mogztter** [opal/opal.github.io#56]
I can see that we are using Opal 1.0.0 in the Gemfile but it seems that the "Try" page still uses Opal 0.11.4?

https://github.com/opal/opal.github.io/blob/c27e633729b460fc07cd20a1d75128d1dc3c51c2/Gemfile#L7

![generated0-11-4](https://user-images.githubusercontent.com/333276/72095761-63d00e80-3319-11ea-899e-33bac62215c4.png)

Notice the "Generated by Opal 0.11.4".
While we are at it, we should probably remove the extra vertical scrollbar 😉

**Comment by elia** [comment]
Finally fixed, should also have faster loading, the main impediment was https://github.com/opal/opal/pull/2074 and a [rack bug](https://github.com/middleman/middleman/issues/2309#issuecomment-575607760)

I don't see the extra scroll bar locally, can you look into it and propose a fix?
