### ISSUE TITLE
can't define own class of User inheriting from other class

### ISSUE THREAD

**Issue by moger777** [opal/opal.github.io#6]
Not sure if this is worth fixing, but you can't create your own version of User and inherit from another class in the try opal section due to the user class already being defined. For example:

```ruby
class User < CustomClass
end
```

will fail with a TypeError: superclass mismatch for class User error. Not sure how trivial it would be to reset all global state set in the editor.

**Comment by vais** [comment]
@adambeynon in my humble opinion this issue should be closed without changing the current behavior. The way it works now is very much in line with what one would expect coming from irb or pry, which is that the environment is "live" and any classes or constants defined in a previous execution are available in the next execution. If one wanted to reset the environment, one can always hit F5 :) The value provided by having a "live" environment far outweighs any potential negatives.

**Comment by elia** [comment]
I agree with @vais fwiw
